version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Azure/service-catalog-cli
    docker:
      - image: quay.io/deis/go-dev:v1.2.0
    steps:
      - checkout
      - run:
          name: Run Build
          command: make build
  test:
    working_directory: /go/src/github.com/Azure/service-catalog-cli
    docker:
       - image: quay.io/deis/go-dev:v1.2.0
    steps:
      - checkout
      - run:
          name: Run Tests
          command: make test
  verify-vendor:
    working_directory: /go/src/github.com/Azure/service-catalog-cli
    docker:
       - image: quay.io/deis/go-dev:v1.2.0
    steps:
      - checkout
      - run:
          name: Verify vendor/
          command: make verify-vendor
  deploy:
    working_directory: /go/src/github.com/Azure/service-catalog-cli
    docker:
      - image: quay.io/deis/go-dev:v1.2.0
    steps:
      - checkout
      - run:
          name: Deploy
          command: make deploy
workflows:
  version: 2
  build-and-test-pr:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              ignore: master
      - build:
          requires:
            - hold
          filters:
            branches:
              ignore: master
      - verify-vendor:
          requires:
            - hold
          filters:
            branches:
              ignore: master
      - test:
          requires:
            - hold
            - build
          filters:
            branches:
              ignore: master
  build-and-test-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - verify-vendor:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
  build-and-test-tags:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - verify-vendor:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - test:
          requires:
            - build
          filters:
            branches:
              # this is a hack, because ignore seems to block all PR builds
              # from completing. We have filed an issue with CircleCI about this
              only: noexist
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - deploy: # Only deploy tagged releases
          requires:
            - verify-vendor
            - test
          filters:
            branches:
              # this is a hack, because ignore seems to block all PR builds
              # from completing. We have filed an issue with CircleCI about this
              only: noexist
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
