version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Azure/service-catalog-cli
    docker:
      - image: quay.io/deis/go-dev:v1.2.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: make dependencies
      - run:
          name: Run Build
          command: make build
  test:
    working_directory: /go/src/github.com/Azure/service-catalog-cli
    docker:
       - image: quay.io/deis/go-dev:v1.2.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: make dependencies
      - run:
          name: Run Tests
          command: make test
  deploy:
    working_directory: /go/src/github.com/Azure/service-catalog-cli
    docker:
      - image: quay.io/deis/go-dev:v1.2.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: make dependencies
      - run:
          name: Deploy
          command: make deploy

workflows:
  version: 2
  build-and-test-pr:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              ignore: master
      - build:
          requires:
            - hold
          filters:
            branches:
              ignore: master
      - test:
          requires:
            - hold
            - build
          filters:
            branches:
              ignore: master
  build-and-test-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - deploy: # Only deploy tagged releases
          requires:
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
